name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildAndroid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget

      - name: Install Haxe
        run: |
          wget https://github.com/HaxeFoundation/haxe/releases/download/4.2.5/haxe-4.2.5-linux64.tar.gz
          tar -xvzf haxe-4.2.5-linux64.tar.gz
          sudo mv haxe-4.2.5/haxe /usr/local/bin/
          rm -rf haxe-4.2.5

      - name: Install Android Tools
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '30'

      - name: Setup Java JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 > /dev/null
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib install flixel 4.11.0
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons 2.11.0

      - name: Create Version Tag
        run: echo "${{ github.run_id }}" > VERSION

      - name: Compile Android
        run: haxelib run lime build android -D NO_PRECOMPILED_HEADERS --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: buildAndroid
          path: export/release/android/bin/app/build/outputs/apk/debug