name: Mobile Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  buildAndroid:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Set Haxelib Repository and Install Dependencies
        run: |
          haxelib setup ~/.haxelib
          haxelib install hxcpp 4.2.1 --verbose
          haxelib install lime 7.9.0 --verbose
          haxelib install openfl 9.2.0 --verbose
          haxelib --never install flixel 5.2.2
          haxelib run lime setup flixel
          haxelib --global update haxelib
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui
          haxelib install flixel-addons 3.0.2
          haxelib install tjson
          haxelib install hxjsonast
          haxelib git SScript https://github.com/beihu235/Sscript4.1.0
          haxelib git hxCodec https://github.com/SPLCoding/hxCodec-but-it-works-xd.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit
          haxelib git extension-androidtools https://github.com/MaysLastPlay77/extension-androidtools
          haxelib install hxcpp-debug-server
          haxelib git androiddialogs https://github.com/beihu235/AndroidDialogs
          haxelib git devicelanguage https://github.com/beihu235/devicelanguage
        env:
          HAXELIB_PATH: ~/.haxelib

      - name: Configure Android Environment
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Build Android APK
        run: haxelib run lime build android -release
        env:
          cert_pass: nullfunni
          cert_alias_pass: nullfunni