name: Build Psych Engine for Android

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  buildAndroid:
    name: Build Psych Engine for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib Dependencies
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib install flixel 4.11.0
          haxelib install flixel-addons 2.11.0
          haxelib install flixel-ui
          haxelib install hxcpp 4.2.1
          haxelib git extension-androidtools https://github.com/MaysLastPlay77/extension-androidtools
          haxelib git hxCodec https://github.com/SPLCoding/hxCodec-but-it-works-xd.git
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit
          haxelib install hxcpp-debug-server
          haxelib list

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Configure Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile Psych Engine
        run: |
          haxelib run lime build android -D NO_PRECOMPILED_HEADERS -D HXCPP_CPP11 -D ANDROID=1 --app-version="0.6.3-${{ github.run_id }}" --verbose
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Publish APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PsychEngine-Android
          path: export/release/android/bin/app/build/outputs/apk/debug
          retention-days: 30